apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: landlord-management
data:
  POSTGRES_DB: landlord_management_tz
  POSTGRES_USER: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: landlord-management
type: Opaque
stringData:
  POSTGRES_PASSWORD: password123
